### PR TITLE
Add multinomial sampling support

### PR DESCRIPTION
**Pull request by johnflux**

### CODE REVIEW

**Comment by josephrocca** [comment]
Nice!! I see you're still adding commits here - ping me when you're done

**Comment by johnflux** [comment]
I'm done :)
It looks like this:  The numbers on the right indicate the number of
possible tokens.
Let me know if you don't want the display on the right, I can remove, but
it's cool.

image

**Comment by josephrocca** [comment]
Just tested it - nice work! Will add a tooltip on those numbers and also credit you in readme

**Comment by johnflux** [comment]
Thanks!

**Comment by josephrocca** [comment]
Q: What is the red underline for?

**Comment by johnflux** [comment]
Just means that the number of possible options is greater than 1.  Just to
see what the number is applying to.

**Pull request merged**
